spring-boot-master:
  server-ip: 127.0.0.1

############################### mysql 数据源 #################################
spring:
  datasource:
    url: jdbc:mysql://${spring-boot-master.server-ip}:3306/ch?characterEncoding=UTF-8&serveTimezone=GMT%2b8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource