spring-boot-master:
  server-ip: 47.102.103.62

############################### mysql 数据源 #################################
spring:
  datasource:
    url: jdbc:mysql://${spring-boot-master.server-ip}:9996/oauth?characterEncoding=UTF-8&serveTimezone=GMT%2b8&useSSL=false
    username: root
    password: Aircas.123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: update


  redis:
    database: 0
    host: ${spring-boot-master.server-ip}
    password: 123456
    port: 6379