#spring-boot-master:
#  server-ip: 20.10.0.23
############################### mysql 数据源 #################################
spring:
  datasource:
#    url: jdbc:mysql://${spring-boot-master.server-ip}:3306/ch?characterEncoding=UTF-8&serveTimezone=GMT%2b8
    url: jdbc:mysql://localhost:3306/asset?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
  jpa:
    database: mysql

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#  spring.datasource.platform = mysql
#  spring.jpa.database = mysql